---
variables:
  IMAGE_ANSIBLE: registry.gitlab.com/pl.rachuna-net/artifacts/containers/ansible:1.1.1
  IMAGE_BUILDAH: registry.gitlab.com/pl.rachuna-net/artifacts/containers/buildah:1.1.0
  IMAGE_CODEX: registry.gitlab.com/pl.rachuna-net/artifacts/containers/codex:1.1.1
  IMAGE_CONFTEST: registry.gitlab.com/pl.rachuna-net/artifacts/containers/conftest:1.1.0
  IMAGE_OPENTOFU: registry.gitlab.com/pl.rachuna-net/artifacts/containers/opentofu:1.1.1
  IMAGE_PYTHON: registry.gitlab.com/pl.rachuna-net/artifacts/containers/python:1.1.0
  IMAGE_RENOVATE: registry.gitlab.com/pl.rachuna-net/artifacts/containers/renovate:1.1.0
  IMAGE_SEMANTIC_RELASE: registry.gitlab.com/pl.rachuna-net/artifacts/containers/semantic-release:1.1.0
  IMAGE_TRIVY: registry.gitlab.com/pl.rachuna-net/artifacts/containers/trivy:1.1.0
